spring:
  application:
    name: Boot-Vagas

  datasource:
    url: jdbc:postgresql://localhost:5433/${POSTGRES_DB}
    password: "${POSTGRES_PASSWORD}"
    username: "${POSTGRES_USER}"
    driver: org.postgresql.Driver

  jpa:
   hibernate:
      ddl-auto: none
   show-sql: true
   properties:
     hibernate:
       format_sql: true
       dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
     enabled: true
     locations: classpath:db/migration