spring:
  application:
    name: Boot-Vagas

  datasource:
    url: jdbc:postgresql://localhost:5432:botVagas
    password: admin
    username:
    driver: org.postgresql.Driver

  jpa:
   hibernate:
      dll-auto: update
   show-sql: true
   properties:
     hibernate:
       format_sql: true
       dialect: org.postgresql.dialect.PostgreSQLDialect
